### ISSUE TITLE
tables with 1 column do not render 

### ISSUE THREAD

**Issue by aghaynes** [CTU-Bern/btabler#13]
**Describe the bug**

![grafik](https://user-images.githubusercontent.com/6594028/123935266-5a66b600-d994-11eb-8bd5-df20bea5ee88.png)

Courtesy of @ArnaudKunzi

**Comment by ArnaudKunzi** [comment]
Reproducible example:

```
library(btabler)
df <- data.frame(out_t = c("Total", "t1", "t1"))
btable(df, nhead = 1, nfoot = 0, caption = "Table1")
```

**Comment by lbueti** [comment]
If there is one row and one header, there is no table left... It works with nhead = 0. Not sure if it is worth to adapt the code for this rather uncommon situation. Maybe just a warning?

**Comment by lbueti** [comment]
Should be fixed now.
