### ISSUE TITLE
more helpful message when nnewline is too small

### ISSUE THREAD

**Issue by aghaynes** [CTU-Bern/btabler#14]
**Is your feature request related to a problem? Please describe.**
Unclear error message generated when nnewline is too small to cut the first word
![grafik](https://user-images.githubusercontent.com/6594028/125044842-a86a7080-e09c-11eb-9d02-2338de13d75c.png)

**Describe the solution you'd like**
clearer error message

Another alternative would be to automatically cut it at end of the longest first word...

**Comment by lbueti** [comment]
Should be fixed now. Provides a warning and splits after the long word.
