### ISSUE TITLE
header doesnt respect aligntot

### ISSUE THREAD

**Issue by aghaynes** [CTU-Bern/btabler#16]
**Describe the bug**
In this example, the aligntot argument is ignored... 
![grafik](https://user-images.githubusercontent.com/6594028/126998146-4b0e95cd-ef30-4594-b202-97460c3128b6.png)

![grafik](https://user-images.githubusercontent.com/6594028/126998067-f865257f-b022-4f21-9973-f07e31e82a40.png)

(nnewline also produces an error 
![grafik](https://user-images.githubusercontent.com/6594028/126998371-625a80c3-f207-4cc0-8cfd-e0bbb0f2ed60.png)
but that is something else entirely...)

**Comment by lbueti** [comment]
The problem is that multicolumn does not respect the alignment. And for the header, multicolumn is used by default to aggregate headers with the same names.
If you use aggregate=FALSE it should work.

**Comment by lbueti** [comment]
I added a warning if aligntot is used with aggregate==TRUE
