### ISSUE TITLE
allow the variable names to included in the data

### ISSUE THREAD

**Issue by aghaynes** [CTU-Bern/btabler#20]
**Is your feature request related to a problem? Please describe.**
Particularly for tables created in R, it can be desirable to print the column names in the table. `btable` doesnt seem to allow this currently as it sets the `include.colnames` argument of `xtable` to FALSE

**Describe the solution you'd like**
pass `include.colnames` argument (or similar) in

**Comment by lbueti** [comment]
done

**Comment by lbueti** [comment]
done
