### ISSUE TITLE
remove \u0002 (start of text) character

### ISSUE THREAD

**Issue by aghaynes** [CTU-Bern/btabler#23]
**Is your feature request related to a problem? Please describe.**
Latex refused to print a particular character, referring to it as \U+0002. 

**Describe the solution you'd like**
Automatic handling of this character - removal is probably sufficient.

**Describe alternatives you've considered**
`str_remove_all(var, "\u0002")` seems to work, but it could be integrated into the sanitzer.

**Comment by lbueti** [comment]
Done
