### ISSUE TITLE
three special characters not converted properly using unicode

### ISSUE THREAD

**Issue by aghaynes** [CTU-Bern/btabler#3]
**Describe the bug**
mu and the degree symbol are not converted to latex properly... 

tests are commented out, [see here](https://github.com/CTU-Bern/btabler/blob/d63671ce3e4b3357444979bc7c5e24ce2227cd01/tests/testthat/tests-sf.R#L24)

**To Reproduce**
uncomment the three lines in tests-sf.R and rerun the test

**Additional context**
Due to an encoding issue?

**Comment by lbueti** [comment]
solved
